### ISSUE TITLE
make all breaks

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#231]
```
sb@arcadia:~/projects/scipy_proceedings/publisher$ make all
rm -rf ../output/* _build/*
mkdir -p _build/tex
./build_template.py title.tex
Traceback (most recent call last):
  File "./build_template.py", line 7, in <module>
    import tempita
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 295
    except SyntaxError, e:
                      ^
SyntaxError: invalid syntax
make: *** [_build/tex/title.tex] Error 1

```

wtf

**Comment by sbenthall** [comment]
it's because it's still in Python 2. worked around it
