### ISSUE TITLE
make html breaks

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#234]
```
cp _build/tex/proceedings.pdf _build/pdfs/proceedings.pdf 
python build_html.py
/bin/sh: 1: recode: not found
Traceback (most recent call last):
  File "build_html.py", line 29, in <module>
    html_from_tmpl(dest_fn+'.html', proc_dict, dest_fn)
  File "/home/sb/projects/scipy_proceedings/publisher/build_template.py", line 56, in html_from_tmpl
    content =  _from_template(src, config)
  File "/home/sb/projects/scipy_proceedings/publisher/build_template.py", line 24, in _from_template
    template = tempita.HTMLTemplate(open(tmpl, 'r').read())
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 131, in __init__
    self._parsed = parse(content, name=name, line_offset=line_offset, delimeters=self.delimeters)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 823, in parse
    next_chunk, tokens = parse_expr(tokens, name)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 869, in parse_expr
    return parse_for(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 955, in parse_for
    next_chunk, tokens = parse_expr(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 869, in parse_expr
    return parse_for(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 955, in parse_for
    next_chunk, tokens = parse_expr(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 854, in parse_expr
    return parse_cond(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 893, in parse_cond
    next_chunk, tokens = parse_one_cond(tokens, name, context)
  File "/home/sb/projects/scipy_proceedings/publisher/tempita/__init__.py", line 909, in parse_one_cond
    assert 0, "Unexpected token %r at %s" % (first, pos)
AssertionError: Unexpected token " if 'org' in member " at (12, 51)
make: *** [proceedings-html] Error 1
rm _build/tex/students.tex _build/tex/copyright.tex _build/tex/organization.tex _build/tex/title.tex

```

**Comment by sbenthall** [comment]
The problematic line is here:

https://github.com/scipy-conference/scipy_proceedings/blob/master/publisher/_templates/organization.html.tmpl#L12
