### ISSUE TITLE
Cannot build paper - TypeError: set_table_style() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by TheChymera** [scipy-conference/scipy_proceedings#268]
I forked the repository so that I can start preparing my paper. My paper fails to build, but it turns out, so does the example paper:

```
chymera@zenbookhost ~/docsrc/scipy_proceedings $ ./make_paper.sh papers/00_vanderwalt
Building: 00_vanderwalt
Traceback (most recent call last):
  File "publisher/build_paper.py", line 229, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 214, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 90, in rst2tex
    settings_overrides=settings)
  File "/usr/lib64/python2.7/site-packages/docutils/core.py", line 414, in publish_string
    enable_exit_status=enable_exit_status)
  File "/usr/lib64/python2.7/site-packages/docutils/core.py", line 662, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/usr/lib64/python2.7/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/lib64/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib64/python2.7/site-packages/docutils/writers/latex2e/__init__.py", line 241, in translate
    visitor = self.translator_class(self.document)
  File "/home/chymera/docsrc/scipy_proceedings/publisher/writer/__init__.py", line 61, in __init__
    self.active_table.set_table_style('booktabs')
TypeError: set_table_style() takes exactly 3 arguments (2 given)
Error building paper papers/00_vanderwalt. Aborting.
```
 Can you help me out?

**Comment by mpacer** [comment]
Are you currently on 2017 or master branch?

**Comment by mpacer** [comment]
Did you run `pip install -r requirements.txt -U`?

**Comment by TheChymera** [comment]
It seems to have been docutils, I was using version 0.13.1 . I checked the requirements, and otherwise I look set. However, I am now getting [this other issue](https://github.com/scipy-conference/scipy_proceedings/issues/270). Can you give me a hand with that as well?
