### ISSUE TITLE
File encoding defaults to ascii

### ISSUE THREAD

**Issue by gpoore** [scipy-conference/scipy_proceedings#288]
The build server is failing with my paper. I believe this is due to vowels with umlauts in some of my references. `publisher/build_paper.py` line 86 should probably add an encoding:
```python
with io.open(rst, mode='r', encoding='utf8') as f:
```
Otherwise, it appears that papers would need to be pure ascii, which would mean a lot more raw LaTeX in the `.rst` source.

Build server output:
```
[ 30/05 19:16 Build failed ] BespON by gpoore 
• Updating proceedings build tools in /Users/mpacer/procbuild/procbuild/../cache/scipy_proceedings...
Already up-to-date.
• Check out paper repository...
Cloning into '/var/folders/4g/_4bqg1_d4ks19t24k1d7pbxm0000h1/T/tmpnglbnfxm'...
Installing proceedings build tools...
• Build the paper...
Building: geoffrey_poore
Traceback (most recent call last):
File "publisher/build_paper.py", line 229, in 
build_paper(paper_id)
File "publisher/build_paper.py", line 214, in build_paper
rst2tex(in_path, out_path)
File "publisher/build_paper.py", line 87, in rst2tex
content = header + f.read()
File "/Users/mpacer/anaconda3/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 32272: ordinal not in range(128)
Error building paper /var/folders/4g/_4bqg1_d4ks19t24k1d7pbxm0000h1/T/tmpnglbnfxm/papers/geoffrey_poore. Aborting.
Error code 1
```

**Comment by mpacer** [comment]
Thank you for catching this as well. A few places have this bug, but are fixed as of #289. 

This is what I get for having a UTF-8 as the `locale.getpreferredencoding()` on my local machine on which I've been testing the py3 compatibility changes :).
