### ISSUE TITLE
Error compiling rst to tex with tables

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#535]
Hi,
I'm trying to write a paper using your template. When I include this fragment from the examples in my code
```rst
.. table:: This is the caption for the materials table. :label:`mtable`

   +------------+----------------+
   | Material   | Units          |
   +============+================+
   | Stone      | 3              |
   +------------+----------------+
   | Water      | 12             |
   +------------+----------------+
   | Cement     | :math:`\alpha` |
   +------------+----------------+
```
I'm receiving this error message. I don't understand the error, since I copied the code directly from the example. Any clues?

```
± % ./make_paper.sh papers/ralph_kube                                                                                                                                                                                              !10171
Building: ralph_kube
Traceback (most recent call last):
  File "publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 91, in rst2tex
    tex = dc.publish_string(source=content, writer=writer,
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 407, in publish_string
    output, pub = publish_programmatically(
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 665, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 251, in translate
    self.document.walkabout(visitor)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 2008, in dispatch_departure
    return method(node)
  File "/Users/ralph/uni/paper/scipy_proceedings/publisher/writer/__init__.py", line 386, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 2966, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error building paper papers/ralph_kube. Aborting.
```

**Comment by mepa** [comment]
Hi @rkube. Thanks for posting this. I recently ran in to the same and logged the issue and a solution here: https://github.com/scipy-conference/scipy_proceedings/issues/534.

For now please `pip install docutils==0.14`. I'll also submit an MR to pin the version in requirements.txt.
