### ISSUE TITLE
Example papers don't compile

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#536]
Hi,
the example papers don't compile on my system:

```bash
$ ./make_paper.sh papers/00_bibderwalt 
Building: 00_bibderwalt
Traceback (most recent call last):
  File "publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 91, in rst2tex
    tex = dc.publish_string(source=content, writer=writer,
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 407, in publish_string
    output, pub = publish_programmatically(
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 665, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 251, in translate
    self.document.walkabout(visitor)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 2008, in dispatch_departure
    return method(node)
  File "/Users/ralph/uni/paper/scipy_proceedings/publisher/writer/__init__.py", line 386, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 2966, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error building paper papers/00_bibderwalt. Aborting.
```

And
```bash
$ ./make_paper.sh papers/00_vanderwalt 
Building: 00_vanderwalt
Traceback (most recent call last):
  File "publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 91, in rst2tex
    tex = dc.publish_string(source=content, writer=writer,
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 407, in publish_string
    output, pub = publish_programmatically(
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 665, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 251, in translate
    self.document.walkabout(visitor)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/nodes.py", line 2008, in dispatch_departure
    return method(node)
  File "/Users/ralph/uni/paper/scipy_proceedings/publisher/writer/__init__.py", line 386, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File "/Users/ralph/miniconda3/envs/scipy_paper/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 2966, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error building paper papers/00_vanderwalt. Aborting.
```

These are my packages with version numbers:
```bash
$pip list
Package         Version            
--------------- -------------------
arrow           0.15.5             
attrs           19.3.0             
binaryornot     0.4.4              
certifi         2020.4.5.1         
chardet         3.0.4              
docutils        0.16               
future          0.18.2             
idna            2.9                
jinja2-time     0.2.0              
lxml            4.5.0              
more-itertools  8.2.0              
nameparser      1.0.6              
packaging       20.3               
pip             20.0.2             
pluggy          0.13.1             
poyo            0.5.0              
py              1.8.1              
Pygments        2.6.1              
pyparsing       2.4.7              
pytest          5.4.1              
python-dateutil 2.8.1              
requests        2.23.0             
setuptools      46.1.3.post20200330
six             1.14.0             
testpath        0.4.4              
urllib3         1.25.8             
wcwidth         0.1.9              
wheel           0.34.2             
whichcraft      0.6.1   
```

Any ideas?

**Comment by mepa** [comment]
@rkube, this is the same issue found in https://github.com/scipy-conference/scipy_proceedings/issues/535. Please pin your `docutils` version to `0.14`, then try again and post back here whether that fixed it!

**Comment by rkube** [comment]
Thanks @mepa  the example papers compile fine with docutils==0.14.

**Comment by mepa** [comment]
Great, thanks for posting back. I've submit PR https://github.com/scipy-conference/scipy_proceedings/pull/538 to ensure others don't hit this. 
Closing the issue.
