### ISSUE TITLE
make_paper.sh failing with a lambda error?

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#545]
```
$ ./make_paper.sh papers/benthall_seth
Building: benthall_seth
Traceback (most recent call last):
  File "publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 92, in rst2tex
    settings_overrides=settings)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/core.py", line 416, in publish_string
    enable_exit_status=enable_exit_status)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/writers/latex2e/__init__.py", line 242, in translate
    self.document.walkabout(visitor)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/nodes.py", line 191, in walkabout
    visitor.dispatch_departure(self)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/nodes.py", line 1925, in dispatch_departure
    return method(node)
  File "/home/sb/projects/econ-ark/scipy_proceedings/publisher/writer/__init__.py", line 386, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File "/home/sb/anaconda3/lib/python3.6/site-packages/docutils/writers/latex2e/__init__.py", line 2955, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error building paper papers/benthall_seth. Aborting.
```

**Comment by mepa** [comment]
Hi @sbenthall. What version of `docutils` are you using? If, e.g., `0.15` or `0.16`, please downgrade to `docutils==0.14` and try again.

Ref: https://github.com/scipy-conference/scipy_proceedings/issues/534

**Comment by sbenthall** [comment]
I have docutils 0.14 installed.

However, if I delete all the tables, it removes the error. So may be related to #544 , #534

**Comment by deniederhut** [comment]
Hey Seb! It's hard to know what's going on without the source paper causing the failure. Do you have an MRE for this bug? Or could you open a PR with your paper?

**Comment by cshewmake2** [comment]
I had the same issue. Downgrading docutils from 0.16 to 0.14 fixed it for me. 
Python3.7, MacOS Mojave 10.14.6.

Strange that it happens still for yours with 0.14. Are you using the same python/pip for installing and running? If you call ./make_paper.sh, it'll call `python`, which may not be the same as `python3` (and its associated pip) depending on your setup.

Just guesses. Curious to hear what ends up working!

**Comment by stsievert** [comment]
I'm also running into the same issue ("TypeError: \<lambda\>() takes 0 positional arguments but 1 was given"). Running `pip install docutils==0.14` solved it for me (thanks to #534).

<details>
<summary>Full traceback </summary>

``` python-traceback
$ bash make_paper.sh papers/scott_sievert
Building: scott_sievert
Traceback (most recent call last):
  File "publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "publisher/build_paper.py", line 92, in rst2tex
    settings_overrides=settings)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/core.py", line 416, in publish_string
    enable_exit_status=enable_exit_status)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/writers/latex2e/__init__.py", line 242, in translate
    self.document.walkabout(visitor)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 178, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 1 more time]
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 191, in walkabout
    visitor.dispatch_departure(self)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/nodes.py", line 1925, in dispatch_departure
    return method(node)
  File "/Users/scott/Developer/stsievert/scipy_proceedings/publisher/writer/__init__.py", line 391, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File "/Users/scott/anaconda3/lib/python3.7/site-packages/docutils/writers/latex2e/__init__.py", line 2955, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Error building paper papers/scott_sievert. Aborting.
```

</details>

**Comment by deniederhut** [comment]
😳 are you already compiling your 2021 paper?

**Comment by deniederhut** [comment]
Closing as fixed
