### ISSUE TITLE
Paper does not build when the first part of the author name is an initial followed by a period

### ISSUE THREAD

**Issue by scottshambaugh** [scipy-conference/scipy_proceedings#713]
I can't seem to put an initial for my first name if there is a period after it. A period somewhere else still works.
Builds: `:author: W Scott Shambaugh`
Builds: `:author: W S. Shambaugh`
Does not build: `:author: W. Scott Shambaugh`

Full trace:
```
<string>:24: (WARNING/2) Cannot extract compound bibliographic field "author".
Traceback (most recent call last):
  File "/home/travel.scott.shambaugh/scipy_proceedings/publisher/build_paper.py", line 237, in <module>
    build_paper(paper_id)
  File "/home/travel.scott.shambaugh/scipy_proceedings/publisher/build_paper.py", line 222, in build_paper
    rst2tex(in_path, out_path)
  File "/home/travel.scott.shambaugh/scipy_proceedings/publisher/build_paper.py", line 91, in rst2tex
    tex = dc.publish_string(source=content, writer=writer,
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/core.py", line 406, in publish_string
    output, pub = publish_programmatically(
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/writers/latex2e/__init__.py", line 242, in translate
    self.document.walkabout(visitor)
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/nodes.py", line 187, in walkabout
    visitor.dispatch_departure(self)
  File "/home/travel.scott.shambaugh/anaconda3/lib/python3.9/site-packages/docutils/nodes.py", line 1895, in dispatch_departure
    return method(node)
  File "/home/travel.scott.shambaugh/scipy_proceedings/publisher/writer/__init__.py", line 172, in depart_document
    self.corresponding = [self.author_names[0]]
IndexError: list index out of range
Error building paper papers/scott_shambaugh/. Aborting.
```

**Comment by deniederhut** [comment]
Weird. This might be a bug in docutils? I won't have time to look into this for at least a couple of days -- are you okay sticking with just W Scott for now?

**Comment by scottshambaugh** [comment]
Yup, not a huge deal!

**Comment by deniederhut** [comment]
Okay we have a solution! The decimal there is confusing the rst parser, but it works if you escape it. So if you do e.g.

```
:author: K\. Jarrod Millman
```

This eventually renders as

<img width="161" alt="Screen Shot 2022-06-04 at 5 09 22 PM" src="https://user-images.githubusercontent.com/6868396/172026960-a5ae6e89-09e2-456b-af82-c03ecc7268dd.png">

**Comment by scottshambaugh** [comment]
Awesome, thank you! That’s an easy enough workaround that I think this issue can close.
