### ISSUE TITLE
How to use include RST directive

### ISSUE THREAD

**Issue by asmeurer** [scipy-conference/scipy_proceedings#799]
I am trying to use the include RST directive to split my paper into multiple documents. However, when I try doing this, I get an error building the paper like:

```
Building: 01_arrayapi
Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/scipy_proceedings/publisher/build_paper.py", line 381, in rst2tex
    rst, = glob.glob(os.path.join(out_path, '*.rst'))
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronmeurer/Documents/scipy_proceedings/publisher/build_paper.py", line 679, in <module>
    build_paper(paper_id)
  File "/Users/aaronmeurer/Documents/scipy_proceedings/publisher/build_paper.py", line 660, in build_paper
    rst2tex(out_path)
  File "/Users/aaronmeurer/Documents/scipy_proceedings/publisher/build_paper.py", line 383, in rst2tex
    raise RuntimeError("Found more than one input .rst--not sure which "
RuntimeError: Found more than one input .rst--not sure which one to use.
Error building paper papers/01_arrayapi/. Aborting.
```

I tried using a different extension from `rst` but then I just get the error

```
docutils.utils.SystemMessage: <string>:866: (SEVERE/4) Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'test.txt'.
```

**Comment by deniederhut** [comment]
Yup so we are doing the foolish thing of assuming there will only be one .rst file, and that the file will be your paper. Would it work to have the include files in a sub-directory?

**Comment by rowanc1** [comment]
This is possible to do now that we are using myst markdown:

https://mystmd.org/guide/embed

Several papers in 2024 did this, both components of Jupyter Notebooks as well as sections of the papers or snippets of code.
